# Use a lightweight Python base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /workspaces/newsletter/summary

# Copy only `requirements.txt` into the container
COPY summary/requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY summary/ .

# Expose the application port
EXPOSE 8080

# Command to run the application
CMD ["python", "summary.py"]
