name: newsletter
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - libexpat=2.6.4
  - libffi=3.4.2
  - libmpdec=4.0.0
  - libsqlite=3.47.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.12.7
  - readline=8.2
  - setuptools=75.3.0
  - tk=8.6.13
  - tzdata=2024b
  - wheel=0.45.0
  - xz=5.2.6
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.39.0
      - anyio==4.6.2.post1
      - blis==1.0.1
      - catalogue==2.0.10
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - cymem==2.0.8
      - distro==1.9.0
      - filelock==3.16.1
      - fsspec==2024.10.0
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.26.2
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.7.1
      - langcodes==3.4.1
      - language-data==1.2.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - networkx==3.4.2
      - numpy==2.0.2
      - openai==1.54.4
      - packaging==24.2
      - preshed==3.0.9
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.4.5
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - smart-open==7.0.5
      - sniffio==1.3.1
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sympy==1.13.1
      - thinc==8.3.2
      - tokenizers==0.20.3
      - torch==2.5.1
      - tqdm==4.67.0
      - transformers==4.46.2
      - typer==0.13.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - wrapt==1.16.0